# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Thu Jun  3 12:44:55 2021
# Model: Habitat Quality

import natcap.invest.habitat_quality
print("InVEST Habitat model : initiated")
args = {
    'half_saturation_constant': '0.075',
    'lulc_cur_path': 'C:/LU-CH_2018.tif',
    'results_suffix': '_18',
    'sensitivity_table_path': 'C:/hab_sensitivity.csv',
    'threat_raster_folder': 'C:/LAYERPROD',
    'threats_table_path': 'C:/18_threats.csv',
    'workspace_dir': 'C:/INVEST/18',
}
print("starting...")

if __name__ == '__main__':
    natcap.invest.habitat_quality.execute(args)

print("...done!")
