# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.12.0 on Wed Nov 16 13:04:10 2022
# Model: Sediment Delivery Ratio

import logging
import sys

import natcap.invest.sdr.sdr
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'biophysical_table_path': 'C:\\bptable_SR.csv',
    'dem_path': 'C:\\DEM_meanLV95_filled.tif',   # filled digital elevation model (using the "fill" tool in ArcGIS pro)
    'drainage_path': '',
    'erodibility_path': 'C:\\Kst_LV95_ch_nib.tif',
    'erosivity_path': 'C:\\rainfall_erosivity_CH.tif',
    'ic_0_param': '0.4',
    'k_param': '2',
    'l_max': '100',
    'lulc_path': 'C:\\LU-CH_2018.tif',
    'n_workers': '-1',
    'results_suffix': '_v2',
    'sdr_max': '0.75',
    'threshold_flow_accumulation': '200',
    'watersheds_path': 'C:\\\\a04_bilanz.shp',
    'workspace_dir': 'C:\\',
}

if __name__ == '__main__':
    natcap.invest.sdr.sdr.execute(args)
