# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Wed Oct 20 16:21:06 2021
# Model: Hydropower Water Yield

import natcap.invest.hydropower.hydropower_water_yield

print("InVEST WY model : initiated")
args = {
    'biophysical_table_path': 'C:/wy_bptable_ds25.csv',
    'depth_to_root_rest_layer_path': 'C:/rrd.tif',
    'do_scarcity_and_valuation': False,
    'eto_path': 'C:/bioclim_chclim25_present_2006_2015_etp.tif',
    'lulc_path': 'C:/LU-CH_2018.tif',
    'pawc_path': 'C:/wsc.tif',
    'precipitation_path': 'C:/bioclim_chclim25_present_2006_2015_prec.tif',
    'results_suffix': '',
    'seasonality_constant': '25',
    'sub_watersheds_path': '',
    'watersheds_path': 'C:/a04_bilanz.shp',
    'workspace_dir': 'C:/',
}

print("...starting")

if __name__ == '__main__':
    natcap.invest.hydropower.hydropower_water_yield.execute(args)
