# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Tue Nov  1 11:05:28 2022
# Model: Crop Pollination

import natcap.invest.pollination

args = {
    'farm_vector_path': '',
    'guild_table_path': 'C:/guild.csv',
    'landcover_biophysical_table_path': 'C:/pollination_bptable_ds25.csv',
    'landcover_raster_path': 'C:/LU-CH_2018.tif',
    'results_suffix': '',
    'workspace_dir': 'C:/invest',
}

if __name__ == '__main__':
    natcap.invest.pollination.execute(args)
